version: '3.7'

services:
  mysql:
    image: docker.io/bitnami/mysql:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=manuel
      - MYSQL_PASSWORD=manuel
      - MYSQL_DATABASE=dwes
    ports:
      - "3306:3306"
    volumes:
      - "./mysql_data:/var/lib/mysql"
  myapp:
    image: docker.io/bitnami/laravel:latest
#    build: ./dockerfile/app
#    user: oem

    container_name: dockerlaravel-main
    ports:
      - '8000-8100:8000-8100'
      - '5170-5180:5170-5180'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=manuel
      - DB_PASSWORD=manuel
      - DB_DATABASE=dwes
#      - dir = app
#      - user = oem
    volumes:
      - './app:/app'
    depends_on:
      - mysql
#    command: chown oem:oem /app -R
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8800:80
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql